# Generated by Django 5.2.4 on 2025-08-05 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=200, verbose_name='Название организации')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo', models.URLField(blank=True, verbose_name='Логотип')),
                ('type', models.CharField(choices=[('clinic', 'Ветеринарная клиника'), ('shop', 'Зоомагазин'), ('pharmacy', 'Аптека'), ('other', 'Другое')], max_length=20, verbose_name='Тип')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('species', models.CharField(choices=[('cat', 'Кот'), ('dog', 'Собака'), ('other', 'Другое')], max_length=10, verbose_name='Вид')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Порода')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес (кг)')),
                ('notes', models.TextField(blank=True, verbose_name='Особые пометки')),
                ('image_url', models.URLField(blank=True, verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата записи')),
                ('clinic', models.CharField(blank=True, max_length=200, verbose_name='Клиника')),
                ('symptoms', models.TextField(blank=True, verbose_name='Симптомы')),
                ('prescription', models.TextField(blank=True, verbose_name='Назначение')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Файлы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Медицинская запись',
                'verbose_name_plural': 'Медицинские записи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductOrService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('product', 'Товар'), ('service', 'Услуга')], max_length=10, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Местоположение')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('image_url', models.URLField(blank=True, verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_services', to='pets.partner')),
            ],
            options={
                'verbose_name': 'Товар/Услуга',
                'verbose_name_plural': 'Товары/Услуги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Событие')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('done', 'Сделано')], default='planned', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['date'],
            },
        ),
    ]
